/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientIdDomesticWireRoutingInfo {
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::RecipientsAddress>,
}

impl RecipientIdDomesticWireRoutingInfo {
    pub fn new(
        account_number: String,
        routing_number: String,
    ) -> RecipientIdDomesticWireRoutingInfo {
        RecipientIdDomesticWireRoutingInfo {
            account_number,
            routing_number,
            address: None,
        }
    }
}
