/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientsAddress {
    #[serde(rename = "address1")]
    pub address1: String,
    #[serde(rename = "address2", skip_serializing_if = "Option::is_none")]
    pub address2: Option<String>,
    #[serde(rename = "city")]
    pub city: String,
    /// Either a two-letter US state code like \"CA\" for California or a free-form identification of a particular region worldwide
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "postalCode")]
    pub postal_code: String,
    /// ISO3166Alpha2
    #[serde(rename = "country")]
    pub country: String,
}

impl RecipientsAddress {
    pub fn new(
        address1: String,
        city: String,
        region: String,
        postal_code: String,
        country: String,
    ) -> RecipientsAddress {
        RecipientsAddress {
            address1,
            address2: None,
            city,
            region,
            postal_code,
            country,
        }
    }
}
