/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientIdElectronicRoutingInfo {
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    /// \"businessChecking\" | \"businessSavings\" | \"personalChecking\" | \"personalSavings\"
    #[serde(rename = "electronicAccountType")]
    pub electronic_account_type: String,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::RecipientsAddress>,
}

impl RecipientIdElectronicRoutingInfo {
    pub fn new(
        account_number: String,
        routing_number: String,
        electronic_account_type: String,
    ) -> RecipientIdElectronicRoutingInfo {
        RecipientIdElectronicRoutingInfo {
            account_number,
            routing_number,
            electronic_account_type,
            address: None,
        }
    }
}
