/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

/// SubmitOnboardingDataFormationDetails : Company formation details.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOnboardingDataFormationDetails {
    /// This must be one of: \"CCorp\", \"LLC\", \"LLP\", \"NonProfit\", \"Partnership\", \"ProfessionalCorporation\", \"SCorp\", \"SoleProprietorship\"
    #[serde(rename = "companyStructure", skip_serializing_if = "Option::is_none")]
    pub company_structure: Option<String>,
    /// Format: 2 digits, optional hyphen, 7 digits.
    #[serde(rename = "federalEin", skip_serializing_if = "Option::is_none")]
    pub federal_ein: Option<String>,
    /// This must be one of: \"ArticlesOfIncorporation\", \"ArticlesOfOrganization\", \"AssumedNameCertificate\", \"BusinessLicense\", \"CertificateOfGoodStanding\", \"CertificateOfLimitedPartnership\", \"LettersTestamentary\", \"OtherBusinessDocumentation\", \"PartnershipAgreement\", \"TrustAgreement\", \"CertificateOfFormation\"
    #[serde(
        rename = "formationDocumentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub formation_document_type: Option<String>,
    /// Base64-encoded (using strict mode) pdf file for state-stamped formation documents.
    #[serde(
        rename = "formationDocumentFileBlob",
        skip_serializing_if = "Option::is_none"
    )]
    pub formation_document_file_blob: Option<std::path::PathBuf>,
    /// PDF for SS-4 document to verify EIN. Base64-encoded (using strict mode).
    #[serde(
        rename = "eINDocumentFileBlob",
        skip_serializing_if = "Option::is_none"
    )]
    pub e_in_document_file_blob: Option<std::path::PathBuf>,
}

impl SubmitOnboardingDataFormationDetails {
    /// Company formation details.
    pub fn new() -> SubmitOnboardingDataFormationDetails {
        SubmitOnboardingDataFormationDetails {
            company_structure: None,
            federal_ein: None,
            formation_document_type: None,
            formation_document_file_blob: None,
            e_in_document_file_blob: None,
        }
    }
}
