/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct About {
    #[serde(rename = "legalBusinessName", skip_serializing_if = "Option::is_none")]
    pub legal_business_name: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    #[serde(rename = "countryOfOperation", skip_serializing_if = "Option::is_none")]
    pub country_of_operation: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<String>,
}

impl About {
    pub fn new() -> About {
        About {
            legal_business_name: None,
            website: None,
            industry: None,
            country_of_operation: None,
            description: None,
            operations: None,
        }
    }
}
