use super::AddressWithoutName;

/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomesticWireRoutingInfoRaw {
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    #[serde(rename = "routingNumber")]
    pub routing_number: String,
    #[serde(rename = "address")]
    pub address: AddressWithoutName,
}

impl DomesticWireRoutingInfoRaw {
    pub fn new(
        account_number: String,
        routing_number: String,
        address: AddressWithoutName,
    ) -> DomesticWireRoutingInfoRaw {
        DomesticWireRoutingInfoRaw {
            account_number,
            routing_number,
            address,
        }
    }
}
