/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    /// Recipient ID from the [/recipients](https://mercurytechnologies.readme.io/reference#recipients-1) endpoint.
    #[serde(rename = "recipientId")]
    pub recipient_id: String,
    /// Amount of USD you want to send, must be a positive number.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Payment method to use, currently only supports \"ach\"
    #[serde(rename = "paymentMethod")]
    pub payment_method: String,
    /// Optional note
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Optional external memo
    #[serde(rename = "externalMemo", skip_serializing_if = "Option::is_none")]
    pub external_memo: Option<String>,
    /// Unique string identifying the transaction
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
}

impl InlineObject2 {
    pub fn new(
        recipient_id: String,
        amount: f64,
        payment_method: String,
        idempotency_key: String,
    ) -> InlineObject2 {
        InlineObject2 {
            recipient_id,
            amount,
            payment_method,
            note: None,
            external_memo: None,
            idempotency_key,
        }
    }
}
