/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject1 {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::RecipientsAddress>,
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
    #[serde(
        rename = "electronicRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub electronic_routing_info: Option<crate::models::RecipientIdElectronicRoutingInfo>,
    #[serde(
        rename = "domesticWireRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub domestic_wire_routing_info: Option<crate::models::RecipientIdDomesticWireRoutingInfo>,
    #[serde(
        rename = "internationalWireRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub international_wire_routing_info:
        Option<crate::models::RecipientIdInternationalWireRoutingInfo>,
}

impl InlineObject1 {
    pub fn new() -> InlineObject1 {
        InlineObject1 {
            name: None,
            address: None,
            emails: None,
            electronic_routing_info: None,
            domestic_wire_routing_info: None,
            international_wire_routing_info: None,
        }
    }
}
