/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::RecipientsAddress>,
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
    /// \"check\" | \"electronic\" | \"domesticWire\" | \"internationalWire\"
    #[serde(rename = "paymentMethod")]
    pub payment_method: String,
    #[serde(
        rename = "electronicRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub electronic_routing_info: Option<crate::models::RecipientsElectronicRoutingInfo>,
    /// Note that all fields in this object are required
    #[serde(
        rename = "domesticWireRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub domestic_wire_routing_info: Option<serde_json::Value>,
    #[serde(
        rename = "internationalWireRoutingInfo",
        skip_serializing_if = "Option::is_none"
    )]
    pub international_wire_routing_info:
        Option<crate::models::RecipientsInternationalWireRoutingInfo>,
}

impl InlineObject {
    pub fn new(name: String, emails: Vec<String>, payment_method: String) -> InlineObject {
        InlineObject {
            name,
            address: None,
            emails,
            payment_method,
            electronic_routing_info: None,
            domestic_wire_routing_info: None,
            international_wire_routing_info: None,
        }
    }
}
