use super::AddressWithoutName;

/*
 * Mercury API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternationalWireRoutingInfoRaw {
    #[serde(rename = "iban")]
    pub iban: String,
    #[serde(rename = "swiftCode")]
    pub swift_code: String,
    #[serde(
        rename = "correspondentRoutingNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub correspondent_routing_number: Option<String>,
    #[serde(rename = "correspondentSwift", skip_serializing_if = "Option::is_none")]
    pub correspondent_swift: Option<String>,
    #[serde(rename = "address")]
    pub address: AddressWithoutName,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "canadianBankCode", skip_serializing_if = "Option::is_none")]
    pub canadian_bank_code: Option<String>,
    #[serde(
        rename = "canadianTransitNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub canadian_transit_number: Option<String>,
    #[serde(rename = "australianBSBCode", skip_serializing_if = "Option::is_none")]
    pub australian_bsb_code: Option<String>,
    #[serde(rename = "indianIFSCCode", skip_serializing_if = "Option::is_none")]
    pub indian_ifsc_code: Option<String>,
}

impl InternationalWireRoutingInfoRaw {
    pub fn new(
        iban: String,
        swift_code: String,
        address: AddressWithoutName,
    ) -> InternationalWireRoutingInfoRaw {
        InternationalWireRoutingInfoRaw {
            iban,
            swift_code,
            correspondent_routing_number: None,
            correspondent_swift: None,
            address,
            phone_number: None,
            canadian_bank_code: None,
            canadian_transit_number: None,
            australian_bsb_code: None,
            indian_ifsc_code: None,
        }
    }
}
